### PR TITLE
Added DeepSource Static Code Analysis

### LINKED ISSUE #9: Add DeepSource Static Code Analysis
## Description 

Add DeepSource Static Code Analysis on this Repository. 

## Additional Details 

- Fork the Repository (If you haven't already) 
- Go through the official [Documentation](https://deepsource.io/docs/analyzer/)
- Setup the `deepsource.toml` on the Root. 
- Make a PR. 

I will activate the analysis from my end to find Bugs and Anti-Patterns at every push.

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
Fixes #9 

Added `.deepsource.toml` file in root

### CODE REVIEW

**Comment by HarshCasper** [comment]
We need a Configuration for Python as well, because the Backend would be on Flask.

**Comment by Siddhant-K-code** [comment]
Updated with Python as well, pls review @HarshCasper

**Comment by HarshCasper** [comment]
Push your Commits into an atomic one. Let me know if you face any blockers 👍

**Comment by Siddhant-K-code** [comment]
how to do this? what is atomic / ? pls explain

**Comment by Siddhant-K-code** [comment]
ohh, i just wanted to close this PR and create a final PR for merging all commits in single !!

**Comment by HarshCasper** [comment]
Let me explain how: 

So, lets say: there were 5 commits in total:

`git reset --soft HEAD~5` will soft reset the last 5 commits.

Then, you can make a single commit by doing the standard `git add` and `git commit`.

And after that, `git push -f origin HEAD` will force push the single commit. I will review the PR right now after which you can make all the changes and push the changes to one commit.

**Pull request closed without merging**
