### PR TITLE
Added the landing page components

### PR DESCRIPTION
**Pull request by shristi99**
Added landing page, My part is Navbar, Welcome page and footer
issue #29

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Is this a follow up to this code: https://github.com/HarshCasper/SpeakEd/pull/51

**Comment by shristi99** [comment]
Yes @HarshCasper

**Comment by HarshCasper** [comment]
Hi @shristi99 

The PR is having merge conflicts. Can you please fix it up so that I can merge your Code as soon as possible?

**Comment by shristi99** [comment]
Fixed the conflict @HarshCasper

**Pull request merged**
