### PR TITLE
Added Logo Designs for SpeakEd

### PR DESCRIPTION
**Pull request by abhishek7997**
Added new logo designs for Speak Ed

Issue #7 

Design Philosophy
1. Microphone design (stand and hand-held)
2. Added the text "Speak Ed" in some design to remove ambiguity about the logo

Colors Used:
1. Light Blue (represents Education) (#a8dadc)
2. Silver Grey (represents Oratory/Speech) (#e5e5e5)

Dark Blue (#457b9d) color is also used for visibility on light backgrounds.

Preview:
image

### CODE REVIEW

**Comment by abhishek7997** [comment]
@HarshCasper Sir, Please look at the logo and give your opinion.

**Comment by HarshCasper** [comment]
I liked this design: 

image

Can you only refer the PNG and the SVG version of this image?

**Comment by abhishek7997** [comment]
@HarshCasper I have removed remaining logos, now check and tell, if it is okay now.

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Remove them from `client` directory and add them in the `design` directory. Check this PR https://github.com/HarshCasper/SpeakEd/pull/40

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Rename the files as: 
- `Logo-Design` -> `logo-design`
- `Working 2 - 1` to `speaked-logo`

**Comment by abhishek7997** [comment]
> Rename the files as:
> 
> * `Logo-Design` -> `logo-design`
> * `Working 2 - 1` to `speaked-logo`

@HarshCasper Done.

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
