### PR TITLE
feat(backend): Added boilerplate

### LINKED ISSUE #3: Add Flask Boilerplate
## AIM 

Add Flask Application and create Mock endpoints for our Flask Application.

## Details

Flask is a micro web framework written in Python. It is classified as a microframework because it does not require particular tools or libraries. We will be using Flask-RESTful for creating the APIs which will interface with the MongoDB Database for Data Persistence.

You have to create basic mock endpoints which return a JSON Message on various routes.

### PR DESCRIPTION
**Pull request by priyanshu20**
# Description

Added flask boilerplate using flask-restful and flask-cors

closes #3 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by priyanshu20** [comment]
@HarshCasper Please review.

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Good Work! 

Few changes required from my Point of View: 

- Add a `README` in the `server` directory stating on how to launch the server.
- Add a note about the importance of `DEBUG` and things to keep in mind before pushing. 
- Add `curl` requests that one can make to access the mock endpoints.

**Review by HarshCasper — APPROVED** [review]
Awesome work! 

Looking forward to your contributions ahead

**Comment by HarshCasper** [comment]
@priyanshu20 : There is a new Issue open for adding authentication routes for the Flask Application. Let me know there if you are interested :)

**Pull request merged**
